version: 2
jobs:
  build:
    docker:
      - image: circleci/node:11.0.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-v1-dependency-{{ .Branch }}-{{ checksum "package-lock.json" }}-{{checksum "headless-chromium"}}
            - node-v1-{{ .Branch }}-
            - node-v1-
      - run: echo "Building zip file"
      - run: npm run build
      - save_cache:
          key: node-v1-dependency-{{ .Branch }}-{{ checksum "package-lock.json" }}-{{checksum "headless-chromium"}}
          paths:
            - ./node_modules
            - ./headless-chromium
      - store_artifacts:
          path: ./lambda.zip
          destination: lambda.zip
      - persist_to_workspace:
          root: .
          paths:
            - lambda.zip
  deploy:
    docker:
      - image: circleci/node:11.0.0
    steps:
      - attach_workspace:
          at: .
      - run: sudo apt-get update -y
      - run: sudo apt-get -y -qq install awscli
      - run: aws lambda update-function-code --function-name pcpoints --region us-east-1 --zip-file fileb://lambda.zip
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
