version: 2
jobs:
  build:
    docker:
      - image: circleci/node:11.0.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-v1-dependency-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - node-v1-{{ .Branch }}-
            - node-v1-
      - run: echo "Building zip file"
      - run: npm run build
      - save_cache:
          key: node-v1-dependency-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
  deploy:
    docker:
      - image: circleci/node:11.0.0
    steps:
      - run: sudo apt-get update -y
      - run: sudo apt-get -y -qq install awscli
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build